### ISSUE TITLE
Поправить захват self

### ISSUE THREAD

**Issue by romaarc** [CT4TuEI3/WeatherApp#11]
https://github.com/CT4TuEI3/WeatherApp/blob/4f107d02212a3a8bf5da5160156bd463004e82e8/WeatherAppTestTask/Modules/MainModule/MainModuleInteractor.swift#L36

Можно `[weak output]` так быстрее

**Comment by CT4TuEI3** [comment]
Не сталкивался с таким ещё. Буду знать.
